In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
y = df['Outcome']

In [5]:
X = df.drop(columns="Outcome",axis = 1)

In [6]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [7]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [10]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
605,1,124,60,32,0,35.8,0.514,21
654,1,106,70,28,135,34.2,0.142,22
478,8,126,74,38,75,25.9,0.162,39
488,4,99,72,17,0,25.6,0.294,28
734,2,105,75,0,0,23.3,0.560,53
...,...,...,...,...,...,...,...,...
708,9,164,78,0,0,32.8,0.148,45
278,5,114,74,0,0,24.9,0.744,57
416,1,97,68,21,0,27.2,1.095,22
492,4,99,68,38,0,32.8,0.145,33
153,1,153,82,42,485,40.6,0.687,23

In [11]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
747,1,81,74,41,57,46.3,1.096,32
322,0,124,70,20,0,27.4,0.254,36
737,8,65,72,23,0,32.0,0.600,42
73,4,129,86,20,270,35.1,0.231,23
333,12,106,80,0,0,23.6,0.137,44
...,...,...,...,...,...,...,...,...
692,2,121,70,32,95,39.1,0.886,23
743,9,140,94,0,0,32.7,0.734,45
506,0,180,90,26,90,36.5,0.314,35
59,0,105,64,41,142,41.5,0.173,22
30,5,109,75,26,0,36.0,0.546,60

In [12]:
from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression()

In [13]:
lgr.fit(X_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
lgr.score(X_test,y_test)

0.7864583333333334

In [ ]:
# Load
# Clean
# Analyse
# Preprocess
# X , y (input output Data)
# Split the Data into Training data testing 
# Choose ML model 
# Fit only Training Data in ML model
# Finally test the model on Testing Data